### ISSUE TITLE
Getting Started build.sbt failed

### ISSUE THREAD

**Issue by ghost** [ThoughtWorksInc/OpenCL.scala#176]
I've copied build.sbt from README.md to my empty build.sbt file.
This error found:
```
build.sbt:2: error: eof expected but ';' found.
libraryDependencies += "com.thoughtworks.compute" %% "gpu" % "latest.release"
^
[error] Error parsing expression.  Ensure that settings are separated by blank lines.
```
OS: Fedora 30
Scala version: Scala code runner version 2.10.6 -- Copyright 2002-2013, LAMP/EPFL
SBT version: sbt launcher version 0.13.1

Thanks in advance!

**Comment by Atry** [comment]
Thank you for reporting.

README is updated right now.
